/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'error-404': RouteRecordInfo<
      'error-404',
      '/:catchAll(.*)*',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/[[locale]]/': RouteRecordInfo<
      '/[[locale]]/',
      '/:locale?',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'changelog': RouteRecordInfo<
      'changelog',
      '/:locale?/changelog',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'howtoplay': RouteRecordInfo<
      'howtoplay',
      '/:locale?/howtoplay',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'patterns': RouteRecordInfo<
      'patterns',
      '/:locale?/patterns',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'pattern': RouteRecordInfo<
      'pattern',
      '/:locale?/patterns/:id',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | 'pattern-form-edit'
    >,
    'pattern-form-edit': RouteRecordInfo<
      'pattern-form-edit',
      '/:locale?/patterns/:id/edit',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | never
    >,
    'pattern-form-new': RouteRecordInfo<
      'pattern-form-new',
      '/:locale?/patterns/new',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'setlists': RouteRecordInfo<
      'setlists',
      '/:locale?/setlists',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'setlist': RouteRecordInfo<
      'setlist',
      '/:locale?/setlists/:id',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | 'setlist-form-edit'
    >,
    'setlist-form-edit': RouteRecordInfo<
      'setlist-form-edit',
      '/:locale?/setlists/:id/edit',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | never
    >,
    'setlist-form-new': RouteRecordInfo<
      'setlist-form-new',
      '/:locale?/setlists/new',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'skins': RouteRecordInfo<
      'skins',
      '/:locale?/skins',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'skin': RouteRecordInfo<
      'skin',
      '/:locale?/skins/:id',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | 'skin-form-edit'
    >,
    'skin-form-edit': RouteRecordInfo<
      'skin-form-edit',
      '/:locale?/skins/:id/edit',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false> },
      | never
    >,
    'skin-form-new': RouteRecordInfo<
      'skin-form-new',
      '/:locale?/skins/new',
      { locale?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false> },
      | never
    >,
    'profile': RouteRecordInfo<
      'profile',
      '/:locale?/users/:id/:tab(patterns|skins|setlists|comments)?',
      { locale?: ParamValueZeroOrOne<true>, id: ParamValue<true>, tab?: ParamValueZeroOrOne<true> },
      { locale?: ParamValueZeroOrOne<false>, id: ParamValue<false>, tab?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...catchAll].vue': {
      routes:
        | 'error-404'
      views:
        | never
      pathParamNames:
        | 'catchAll'
    }
    'src/pages/[[locale]]/index.vue': {
      routes:
        | '/[[locale]]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/changelog.vue': {
      routes:
        | 'changelog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/howtoplay.vue': {
      routes:
        | 'howtoplay'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/patterns/index.vue': {
      routes:
        | 'patterns'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/patterns/[id].vue': {
      routes:
        | 'pattern'
        | 'pattern-form-edit'
      views:
        | 'default'
      pathParamNames:
        | 'id'
    }
    'src/pages/[[locale]]/patterns/[id]/edit.vue': {
      routes:
        | 'pattern-form-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/patterns/new.vue': {
      routes:
        | 'pattern-form-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/setlists/index.vue': {
      routes:
        | 'setlists'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/setlists/[id].vue': {
      routes:
        | 'setlist'
        | 'setlist-form-edit'
      views:
        | 'default'
      pathParamNames:
        | 'id'
    }
    'src/pages/[[locale]]/setlists/[id]/edit.vue': {
      routes:
        | 'setlist-form-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/setlists/new.vue': {
      routes:
        | 'setlist-form-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/skins/index.vue': {
      routes:
        | 'skins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/skins/[id].vue': {
      routes:
        | 'skin'
        | 'skin-form-edit'
      views:
        | 'default'
      pathParamNames:
        | 'id'
    }
    'src/pages/[[locale]]/skins/[id]/edit.vue': {
      routes:
        | 'skin-form-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/skins/new.vue': {
      routes:
        | 'skin-form-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[[locale]]/users/[id]/[[tab]].vue': {
      routes:
        | 'profile'
      views:
        | never
      pathParamNames:
        | 'tab'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
